[pytest]
# 同时扫描接口、UI两个目录
testpaths = api/test_api tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
# 自定义标记
markers =
    api: 接口测试用例
    ui：UI自动化用例
    smoke: 主干冒烟测试用例
    negative: 异常反向测试用例
    regression: 全量回归测试用例
    api: 接口自动化测试
addopts = -v -s --alluredir=allure-results --clean-alluredir --reruns=1 --reruns-delay=1
